---
title: "Pseudopailledema Manuscript"
author: "Melvin Disla"
date: "7/7/2017"
output: html_document
---

Using optical coherence tomography to evaluate retinal nerve fiber layer thickness in pseudopapilledema and papilledema

Mary W. Tam, MS1,2, Kendra Klein MD2, Laurel Vuong MD2, Melvin Disla, BS,2 Thomas R. Hedges III, MD2

1Tufts University School of Medicine, Boston, Massachusetts
2New England Eye Center, Tufts Medical Center, Boston, Massachusetts

Address correspondence to Thomas Hedges III, MD, Director of Neuro-ophthalmology Service, Co-Director of Electrophysiology Service, Professor of Ophthalmology and Neurology. New England Eye Center, 800 Washington St. #450 Boston, MA 02111; E-mail: thedges@tuftsmedicalcenter.org

The authors report no conflict of interest.

Keywords: pseudopapilledema, papilledema, congenitally crowded nerves, OCT, optical coherence tomography



Abstract
Purpose
To evaluate and characterize findings of patients with pseudopapilledema and patients with optic disc edema superimposed on pseudopapilledema by describing cases, assessing the upper-limit and variability of retinal nerve fiber layer (RNFL) thickness on in patients with pseudopapilledema.
Methods
A retrospective observational case series of 19 patients with pseudopapilledema seen at New England Eye Center, Boston from 2010-2017 were described. All patients were referred to the neuro-ophthalmology service based on suspicion of optic nerve head swelling and underwent neuro-ophthalmic examination, fundus photography, and automated visual field testing. Patients with probable papilledema had neuroimaging with or without lumbar punctures (LPs). Each patient underwent longitudinal spectral domain-optical coherence tomography (SD-OCT) imaging for at least 6 months with both 512 x 128 cube scan and the 5-line raster protocol. The average, superior, inferior, nasal, and temporal RNFL thickness of each group was compared. The upper-limit and variability of RNFL thickness of pseudopapilledema were assessed. Two independent observers analyzed and reviewed all patient charts and tests.
Results
24 eyes of 12 patients with pseudopapilledema and 14 eyes of 7 patients with papilledema superimposed on pseudopapilledema were included. Mean age of patients in pseudopapilledema group was 31 years (10-59 years) and in papilledema group 21 years (14-37 years). Eight-three percent of patients were females in pseudopapilledema group and 43% of patients were females in papilledema group superimposed on pseudopapilledema group. Mean duration of follow-up was 26.5 months (7-51 months) in pseudopapilledema group and 31.43 months (6-66 months) in papilledema superimposed on pseudopapilledema group. All seven patients with presumed papilledema had normal neuroimaging except for two patients, one with with empty sella with mild chiari malformation, and one with low cerebellar tonsils with small transverxe venous sinuses. Three of seven patients with presumed papilledema had LPs with opening pressure (OP) ≥250 mm H2O to confirm diagnosis of papilledema. One patient had LP with normal OP, however, developed papilledema secondary to aseptic meningitis 2 months later. Average RNFL thicknesses were significantly greater in patients with papilledema superimposed on pseudopapilledema group compared to pseudopapilledema group. RNFL thickness by quadrants were greater in papilledema superimposed on pseudopapilledema group compared to pseudopapilledema group and were significantly greater in superior, inferior, and nasal quadrants. Upper-limit of patients with pseudopapilledema was 123.79 µm. Variability of average RNFL thickness in patients with pseudopapilledema was ±7.39 µm with a 95% confidence interval.
Conclusions
This paper suggests that careful longitudinal clinical correlation along with neuroimaging and repeated OCTs may indicate presence of pseudopapilledema and/or papilledema. OCT may be used to determine the upper-limit of RNFL thickness in patients with pseudopapilledema. Longitudinal OCTs may be helpful to confirm diagnosis of pseudopapilledema by looking at the trend and variability of RNFL thickness in patients. The use of non-invasive imaging tools such as Cirrus SD-OCTs may promise a fast and easy alternative to diagnostic or repeated lumbar punctures in identifying persistence and resolution of papilledema.

Introduction
The diagnosis of pseudopapilledema with and without optic nerve head drusen is often misdiagnosed as optic disc edema. Pseudopapilledema is a benign finding caused by anomalous, congenital elevation of the optic disc. Calcified deposits, called drusen are typically found at the lamina cribosa of the crowded optic nerve head.1,2 In contrast, papilledema is swelling of the optic disc due to increased intracranial pressure, which can be caused by an identifiable or non-identifiable etiology (also known as idiopathic intracranial hypertension (IIH)).3,4  Papilledema results from orthograde axoplasmic flow obstruction and distension of the prelaminar and peripapillary axons at the optic nerve head leading to edema of the retinal nerve fiber layer from the increased intracranial pressure pressing on the nerve behind the eye.5-7 
In clinical practice, a common dilemma is to distinguish pseudopapilledema from pathologic optic disc edema. Diagnosis and management of pseudopapilledema and papilledema are vastly different. However, frequently, patients with elevated optic discs are almost always referred for neuro-ophthalmologic evaluation and may be subjected to neuroimaging, lumbar puncture, and other laboratory studies. It is more challenging to the practitioner when patients have papilledema superimposed on pseudopapilledema because patients with pseudopapilledema have elevated optic nerve head appearances at baseline. It is important to note that papilledema is a serious clinical sign that may represent underlying threatening intracranial pathology. Similarly, it is as important to recognize features of pseudopapilledema to avoid unnecessary costly and invasive tests. 
Optical coherence tomography (OCT), a non-invasive imaging method, which creates in vivo cross sections of the retina, has been a valuable tool and is used to understand some neurological diseases such as optic neuritis, multiple sclerosis, spinocerebellar ataxia, neuromyelitis optica, pituitary tumors and Parkinson’s disease.8 Studies have compared retinal nerve fiber layer (RNFL) thickness in patients with pseudopapilledema and papilledema.9,10 
The purpose of this study is to evaluate and characterize findings of patients with pseudopapilledema and papilledema superimposed pseudopapilledema to help clinicians understand disease progression and resolution by describing patients with papilledema superimposed on pseudopapilledema, assessing the upper-limit of RNFL thickness in patients with pseudopapilledema, identifying differences in variability of RNFL measurements of patients during follow-up, and proposing recommendations on how to approach patients with pseudopapilledema.
Materials and Methods
Participants
The study was approved by the Institutional Review Board of the Tufts University School of Medicine. The research adhered to the tenets of the Declaration of Helsinki and is in accord with Health Insurance Portability and Accountability Act regulations. Informed consent was considered exempt for the study due to its retrospective design by the Institutional Review Board. 
This is a retrospective longitudinal observational case series. Data was collected from 2010-2017, a 6-year period, from the database of patients of the neuro-ophthalmology service at New England Eye Center at Tufts Medical Center, Boston Massachusetts. Keyword searches of patients in the database include pseudopapilledema, congenitally crowded nerves, papilledema, and idiopathic intracranial hypertension. All patients included in the study were referred to the neuro-ophthalmology department for suspicion of elevated optic nerve head. Patients provided detailed medical and ocular history and underwent complete neuro-ophthalmic evaluation, slit-lamp examination, automated visual field testing, color fundus photographs by a professional photographer. Inclusion criteria were patients with at least two neuro-ophthalmic visits with duration of more than six months, in addition to serial imaging of the optic nerve head with high definition spectral domain-optical coherence tomography (Cirrus HD-OCT; Carl Zeiss Meditec, Inc., Dublin CA) to monitor changes compared to their initial presentation. Papilledema was defined as clinically optic nerve head swelling due to increased intracranial pressure with a known cause or caused by IIH. Pseudopapilledema was defined as optic nerve head elevation present in combination with crowding of the optic nerve head without presence of buried drusen. We included patients with adequate follow-up duration with specific documentation of changes or absence of changes in optic nerve head appearance by a neuro-ophthalmologist. Patients with prior orbital surgeries, co-existing retinal or other optic nerve pathologies, obvious optic nerve head drusen and Stratus OCTs were excluded from the study. 
Chart review and analysis were done by 2 observers to record findings consistent with papilledema or pseudopapilledema. Groups were divided into pseudopapilledma and papilledema superimposed on pseudopapilledema. All patients with the presumed diagnosis of papilledema underwent neuroimaging, which included a magnetic resonance imaging (MRI),  magnetic resonance venography (MRV) or computerized tomography (CT) with or without lumbar puncture. Modified Dandy criteria by Friedman and Jacobson included presence of symptoms or signs solely attributed to intracranial hypertension or papilledema, no neurological deficits other than a 6th cranial nerve palsy, a documented elevated intracranial pressure measured in the lateral decubitus position, normal CSF composition, normal neuro-imaging found on MRI, MRV, or CT, no other causes of increased ICP found, and a diagnosis is deemed probable if all other criteria are met but no lumbar puncture is performed to determine opening pressure.11 Clinical features of IIH including headaches, tinnitus, or visual obscuration, body habitus of IIH, presence of thickened retinal fiber layer on OCT, and normal neuroimaging were monitored. Sequential HD-OCT were analyzed to determine trend and variability over time.
OCT Measurement and Analysis
Longitudinal Cirrus HD-OCT imaging with cube scan consisting of 512 A-scans x 128 B-scans centered on the optic disc and a HD 5-line raster scan centered on the optic disc of both eyes on Cirrus HD-OCT (Carl Zeiss Meditec Inc, Dublin, CA, version 7.0.319) data were collected. The 5-line raster protocol is a 6-mm line scan that acquires 4,096 A-scans in each of the five lines. The enhanced depth imaging (EDI)-OCT protocol on the Cirrus device could not be employed, as it was not available during the time when most of these scans were performed. OCT was done at each visit to qualitatively and quantitatively identify features between pseudopapilledema and papilledema. Specifically, in the papilledema superimposed on pseudopapilledema group, OCT was used to monitor disease progression and resolution. Two independent reviewers analyzed and reviewed morphology of RNFL thickness on OCT. RNFL thickness analysis were performed on each eye of all patients. RNFL thickness in all four quadrants were compared longitudinally and across all patients. 
Statistical Analysis
Statistical analyses were performed using R studio version 2.13.0 statistical software (RStudio: Integrated Development for R. RStudio, Inc., Boston, Massachusetts) and graphs were created using GraphPad Prism version 7.0 software (GraphPad Software, La Jolla, California). OCT measurements were compared between pseudopapilledema group (Group 1) and papilledema group (Group 2). Descriptive statistics of data set including minimum, maximum, mean, median, standard deviation and first and third quartiles for quantitative variables including baseline age, follow-up duration, RNFL thickness in all quadrants (superior, inferior, nasal, and temporal) and average RNFL were used. Welch two sample t-test was applied to compare the mean RNFL thickness of all quadrants and average RNFL between groups. Upper-limit of pseudopapilledema group was assessed. The upper-limit was defined as two standard deviations above the mean of average RNFL thickness in pseudopapilledema group. Variability of pseudopapilledema group was determined at the 95% confidence interval. A 95% confidence interval and a 5% level of significance were adopted. Results with a p value less than or equal to 0.05 were considered significant. 
Results
Of the 132 pseudopapilledema patients, 19 patients were included in this study. Twenty-four eyes of 12 patients were included in pseudopapilledema group and 14 eyes of 7 patients were included in papilledema superimposed on pseudopapilledema group. Mean age of pseudopapilledema group was 31 years (range 10-63 years) and of papilledema superimposed on pseudopapilledema group was 21 years (range 14-37 years). Eight-three percent were females in pseudopapilledema group and 43% were females in papilledema with pseudopapilledema group. We excluded 2 patients in the pseudopapilledema group with time domain OCT (Stratus, Carl Zeiss Meditec, Dublin, CA) because the data collected was not able to be used interchangeably with Cirrus OCT measurements.12, 13 Three patients with obvious optic disc drusens were excluded in pseudopapilledema group. Mean duration of follow-up was 26.5 months (range 7-51 months) in pseudopapilledema group and 31.4 months (range 6-66 months) in papilledema superimposed on pseudopapilledema group. Demographics of patients are displayed in table 1.
Table 1. Demographics of patients

*When comparing pseudopapilledema and papilledema with pseudopapilledema group, chi-square tests were used for categorical variables and non-paired 2-tailed Student t-tests was used for continuous variables; †Mean (standard deviation); ‡χ2 3.352

Trend of average RNFL thickness of right eye and left eye of patients in pseudopapilledema group and papilledema superimposed on pseudopapilledema group are depicted in figure 1A, B, C, D. Variability of each eye of each patient was determined based on the average RNFL thickness per eye of each patient at initial visit and variability was recorded based on the difference between the average RNFL thickness at initial baseline visit and subsequent visit, displayed in figure 2A, B, C, D. Upper-limit of patients with pseudopapilledema was 123.79 µm based on 2 SD above the mean of average RNFL thickness. Variability of average RNFL thickness in patients with pseudopapilledema was ±7.39 µm with a 95% confidence interval. Table 2 describes the statistical analyses of both groups. When mean average RNFL thickness and RNFL thickness of quadrants were compared, we found statistical significance in mean of average RNFL thickness, inferior quadrant, superior quadrant and nasal quadrant (Table 3).
Table 2. Descriptive statistics of age at presentation, follow-up duration, average RNFL thickness, and RNFL thickness of quadrants 

SD, standard deviation; RNFL, retinal nerve fiber layer; I, inferior; S, superior; N, nasal; T, temporal

Table 3. Mean of average retinal nerve fiber layer thickness and retinal nerve fiber layer quadrants

*Welch two sample t-test
Summary of patients of papilledema superimposed on pseudopapilledema are described in table 4. The severity of disc swelling in this group varied from mild to severe. Three of the 7 patients with papilledema superimposed on pseudopapilledema group had LPs with opening pressure (OP) of more than 250 mm H2O (280-400 mm H2O) and met the modified Dandy criteria. One patient had normal OP of 230 mm H2O, however, she was presumed to have papilledema secondary to aseptic meningitis when she presented two months after lumbar puncture. Based on her clinical presentation and OCT imaging findings, she was started on medical therapy. Her symptoms and papilledema resolved in 2 months with longitudinal follow-up and medical treatment. 
Three of the patients in papilledema superimposed on pseudopapilledema group did not have lumbar punctures to confirmed diagnosis of papilledema. Considering the modified Dandy criteria, they were presumed to have IIH, although they did not have lumbar punctures to confirm diagnosis because they had clinical features of IIH including headaches, tinnitus, or visual obscuration, body habitus of IIH, presence of thickened retinal fiber layer on OCT, and normal neuroimaging. The 3 patients were recommended to have lumbar punctures if symptoms persisted or worsen. Shared decisions were made between the physician and patient when considering non-invasive diagnostic tests and conservative management to monitor progression and resolution of papilledema, which included a trial of weight loss and serial follow-ups to monitor clinical and imaging changes. All patients with papilledema superimposed with pseudopapilledema had resolution of symptoms with longitudinal clinical follow-up, serial OCT imaging, and conservative management.
Table 4. Summary of papilledema cases

*Index case
BCVA, best corrected visual acuity; LP, lumbar puncture; OP, opening pressure
Index case: Papilledema superimposed on pseudopapilledema
This 14-year-old boy was referred by a comprehensive ophthalmologist for possible optic nerve head elevation. He has had headaches since age 8 years old. No history of lumbar punctures performed. At initial presentation, his best-corrected visual acuity (BCVA) was 20/20 in both eyes. Fundus photos showed crowded optic nerve heads. HD-OCT imaging showed average RNFL thickness to be 123 µm in right eye and 131 µm in left eye. One year after initial presentation, he had more optic disc swelling on fundus exam. On OCT imaging, average RNFL thickness was 182 µm in right eye and 164 µm in left eye. Fundus exam and HD-OCT imaging shown in figure 3a and 3b demonstrate findings during onset of optic disc swelling. It was recommended for patient to have an LP to confirm diagnosis, a trial of conservative management including weight-loss, and close monitoring of symptoms. LP was not done at the time of the visit and the plan was to do a trial of weight-loss. At the next follow-up visit, 6 months later, patient had 15-pound weight loss. Repeat OCT at the time showed average RNFL thickness to be 146 µm in right eye and 148 µm in left eye. During his most recent visit in year of 2017, he lost a total of 35 pounds. BVCA and Humphrey visual field testing were unchanged from initial visit. Fundus exam shows crowding of optic nerve head bilaterally and resolution of optic disc swelling in figure 3c and HD-OCT imaging in figure 3d shows crowded optic nerve head. Average RNFL thickness at this visit was 103 µm in right eye and 110 µm in left eye. 
Discussion
The present case series describes longitudinal clinical correlation and the use of serial optical coherence tomography (OCT) imaging to describe findings of congenital crowding without drusen and papilledema superimposed on pseudopapilledema. We further describe the trend, variability, and upper-limit of retinal nerve fiber layer (RNFL) thickness in patients with pseudopapilledema. The results of the study indicate that serial HD-OCT and longitudinal follow-up may be useful in identifying the presence of and difference of pseudopapilledema from papilledema superimposed on pseudopapilledema when comparing retinal nerve fiber layer thickness.
We used Cirrus HD-OCT as the imaging modality to compare two conditions because studies have shown lower measurement variability, higher sensitivity and specificity, repeatability and reproducibility in RNFL thickness measurements when compared to Stratus OCT.14-17 The normal parameters of Cirrus HD-OCT for average RNFL thickness is 75-107.2 µm, for temporal quadrant is 45.1-82.2 µm, for superior quadrant is 88.9-136.7 µm, for nasal quadrant is 50.0-86.2 µm, and for inferior quadrant is 89.4-138.3 µm.18 Here, we demonstrate that the mean of retinal nerve fiber layer thickness in patients with pseudopapilledema and papilledema superimposed on pseudopapilledema fall above the normal parameters of Cirrus HD-OCT except for the inferior quadrant of RNFL thickness in both groups. In this study, there was a significant increase in average RNFL thickness and RNFL thickness of superior, inferior and nasal quadrants in patients with papilledema superimposed on pseudopapilledema compared to patients with pseudopapilledema. The RNFL thickness of temporal quadrant of papilledema superimposed on pseudopapilledema group was increased but was not significant when compared to pseudopapilledema only group. The differences may be explained by the amount of glial support of RNFL bundles in the superior and inferior aspect of the optic disc as opposed to medially and temporally.19 One study found that RNFL thickening was mainly in the inferior and superior peripapillary region and was greater in higher grades of papilledema.20 
Differentiating papilledema from pseudopapilledema is a diagnostic dilemma; it is more challenging to determine patients with pseudopapilledema who then develop papilledema. The confirmation of diagnosis has significant implications for appropriate patient management and important of reducing patient costs and anxiety.21 In this study, we specifically looked at patients with congenital crowding without drusen and papilledema because the two conditions are more difficult to distinguish clinically.1 Often, patients with pseudopapilledema undergo superfluous tests and imaging to confirm diagnosis. In one study, of patients under age of 22 with suspected IIH or papilledema, almost half of diagnoses were revised to pseudopapilledema and many patients had unnecessary lumbar punctures, MRIs, CTs, and some patients were taking medications, which were discontinued upon revision of the diagnoses.22 
Martinez et al. found OCT to be a reliable adjunctive tool in the differentiation of newly diagnosed papilledema and pseudopapilledema in young patients.23 Huang-Link et al. demonstrated that SD-OCT allows detection of optic nerve head changes even in subtle IIH without papilledema.24 Kupersmith et al. used OCT to look at the morphology of retinal nerve fiber layer in patients with papilledema and found that there is deformation of optic nerve head from raised intracranial pressure to show that the retinal pigmented epithelium/Bruch’s membrane (RPE/BM) is commonly deflected inward. 25 In this present study, we demonstrated that OCT may be helpful in monitoring progression and resolution of papilledema.
We determined the upper-limit of average RNFL thickness and variability of RNFL thickness of patients with pseudopapilledema in our study. The variability of average RNFL thickness is comparable to previous studies, which showed approximately 5-15 µm variability between each session.15,26 Given the findings in this study, when ophthalmologists, optometrists, neurologists, and neuro-ophthalmologists encounter a new patient with suspicion of elevated optic nerve head, they may use HD-OCT as part of the initial workup, along with complete history, ophthalmic exams, and other ophthalmic tests. With the use of HD-OCT, if RNFL thickness is less than the upper-limit of pseudopapilledema as described in this paper, then we recommend serial follow-up for at least 6 months with repeated complete ophthalmic exams and OCT imaging. If variability is approximately ±7.39 µm at 6th month visit, this will increase the likelihood that the patient has pseudopapilledema, given the patient does not have signs and symptoms of increased intracranial pressure. However, if RNFL thickness of initial visit is above the upper-limit of pseudopapilledema, an approach to consider is to obtain neuroimaging to rule out masses that may cause papilledema, when neuroimaging is normal, and there are no other neurological deficits, one can presume that patient has probable papilledema. It is necessary to follow patients longitudinally to monitor symptoms and changes in OCT imaging. Clinicians may begin with conservative management on patients such as weight-loss; however, if systemic and visual symptoms worsen or if variability is abovea ±7.39 µm on repeat OCT, then additional imaging, diagnostic tests such as lumbar puncture, and neurological workup is recommended.
Although, we showed that the RNFL thickness of patients with pseudopapilledema are different from papilledema superimposed on pseudopapilledema, previous studies demonstrated that pseudopapilledema and mild papilledema may be difficult to differentiate by OCT alone.1, 27 Costello explained that variability is greater in serial measure of OCT in patients with pseudopailledema.8 Thus, in cases where differentiation between these two conditions is uncertain, additional imaging and appropriate neurologic workup is indicated. If OCT imaging is used in clinical practice to evaluate patients, practitioners must ensure the imaging has fair quality and signal strength. Some factors that may be affect signal strength of OCT include older age, poorer best corrected visual acuity (BVCA), greater degree of myopia and presence of cortical and posterior subcapsular cataract.28 When used properly, OCT may be a valuable and fast alternative to invasive diagnostic tests in patients with suspicion of elevated optic nerve head. 
	 The limitations of this study include the small sample size due to a single center study and the exclusion of many participants because of lack of adequate follow-up. Other limitations include lack of standardization of reported clinical findings and tests due to the nature of retrospective studies, variability in diagnostic and treatment modalities in papilledema superimposed on pseudopapilledema group, and difference in timing of OCT imaging between both groups. 
This case series was intended to determine whether longitudinal follow-up with clinical correlation and serial OCT imaging were helpful in assessing upper-limit of RNFL thickness of patients with pseudopapilledema, analyzing the variability of RNFL thickness in patients with pseudopapilledema, and determining differences between pseudopapilledema and papilledema superimposed on pseudopapilledema. The use of Cirrus HD-OCT may promise a rapid and easy alternative to diagnostic or repeated lumbar punctures in monitoring changes and resolution of papilledema.



References
Karam EZ, Hedges TR. Optical coherence tomography of the retinal nerve fibre layer in  mild papilloedema and pseudopapilloedema. Br J Ophthalmol 2005;89:294-8.
Tugcu B. Ozdemir. Imaging Methods in the Diagnosis of Optic Disc Drusen. Turk J Ophthalmol. 2006;46(5):232-236.
Digre KB, Corbett JJ. Idiopathic intracranial hypertension (pseudotumor cerebri): A reappraisal. Neurologist. 2001;7:2-67.
Wall M. Idiopathic intracranial hypertension. Neurol Clin. 1991;9:73-95.
Killer H, Jaggi G, Miller N. Papilledema revisited: is its pathophysiology really understood? Clin Experiment Ophthalmol. 2009;37(5):444-7
Trobe JD. Papilledema: the vexing issues. J Neuroophthalmol. 2011; 31: 175–186
Tso MO Hayreh SS. Optic disc edema in raised intracranial pressure, IV: axoplasmic transport in experimental papilledema. Arch Ophthalmol. 1977; 95: 1458–1462.
Costello F. Optical Coherence Tomography in Neuro-ophthalmology. Neurologic Clinics. 2017;35(1):153-163.
Kulkarni KM, Pasol J, Rosa PR, Lam BL. Differentiating mild papilledema and buried optic nerve head drusen using spectral domain optical coherence tomography. Ophthalmol. 2014;121(4):959-63.
 Bassi ST, Mohana KP. Optical coherence tomography in papilledema and pseudopapilledema with and without optic nerve drusen. Ind J Ophthalmol. 2014; 62(12):1146-1151.
Friedman DI, Liu GT, Digre KB. Revised diagnostic criteria for the pseudotumor cerebri syndrome in adults and children. Neurology. 2013;81:1159-65.
Kim CY, Jung JW, Lee SY, Kim NR. Agreement of retinal nerve fiber layer color codes between stratus and cirrus OCT according to glaucoma severity. Invest Ophthalmol Vis Sci. 2012;53(6):3193-3200.
Huang J, Liu X, Wu Z, Guo X, Xu H, Dustin L, Sadda S. Macular and retinal nerve fiber layer thickness measurements in normal eyes with stratus OCT, the Cirrus HD-OCT and Topcon 3D OCT-1000. J Glaucoma. 2011;20(2):118-125.
Mwanza JC, Oakley JD, Budenz DL, Anderson DR; Cirrus Optical Coherence Tomography Normative Database Study G. Ability of Cirrus HD-OCT optic nerve head parameters to discriminate normal from glaucomatous eyes. Ophthalmol. 2011;118(2):241-248 e241.
Leung CK, Cheung CY, Weinreb RN, Qiu Q, Liu S, Li H, Xu G, Fan N, Huang L, Pang CP, Lam DS. Retinal nerve fiber layer imaging with spectral-domain optical coherence tomography: a variability and diagnostic performance study. Ophthalmol. 2009;116(7):1257-63.
Grewal DS, Tanna AP. Diagnosis of glaucoma and detection of glaucoma progression using spectral domain optical coherence tomography. Curr Opin Ophthalmol. 2013;24(2):150-61.
Sung KR, Kim DY, Park SB, Kook MS. Comparison of retinal nerve fiber layer thickness measured by Cirrus HD and Stratus optical coherence tomography. Ophthalmol. 2009;116(7) 1264-70
Cirrus HD-OCT: How to read the Cirrus reports. 2011 Available from: https://www.zeiss.co.uk/content/dam/Meditec/gb/Chris/OCT%20Business%20Builder/PDF's/1.pdf
Quigley HA, Addicks EM. Quantitative studies of retinal nerve fiber layer defects. Arch Ophthalmol. 1982;100:807–14.
Ahuja S, Anand D, Dutta TK, Ropesh Kumar VR, Sekat Kar, Sitanshu. Retinal nerve fiber layer thickness analysis in cases of papilledema using optical coherence tomography-a case control study. Clin Neuro and Neurosurg. 2015;136:95-99.
Chiang J, Wong E, Whatham A, Hennessey M, Kalloniatis M, Zangeri B. The usefulness of multimodal imaging for differentiating pseudopapiledema and true swelling of the optic nerve head: a review and case series. Clin Exp Optom. 2015;98(1): 12-24.
Liu B, Murphy RK, Mercer D, Tychsen L, Smyth MD. Pseudopapilledema and association with idiopathic intracranial hypertension. Childs Nerv Syst. 2014;30(7):1197-200.
Martinez MR, Ophir A. Optical coherence tomography as an adjunctive tool for diagnosing papilledema in young patients. J Pediatr Ophthalmol Strabismus. 2011;48(3)174-81.
Huang-Link YM, Al-Hawasi A, Oberwahrenbrock T, Jin YP. OCT measurements of optic nerve head changes in idiopathic intracranial hypertension. Clin Neurol Neurosurg. 2015;130:122-7.
Kupersmith MJ, Sibony P, Mandel G, Durbin M, Kardon RH. Optical coherence tomography of the swollen optic nerve head: deformation of the peripaillary retinal pigment epithelium layer in papilledema. Invest Ophthalmol Vis Sci. 2011;52(9):6558-6564.
Bundenz DL, Fredette MJ, Feuer WJ, Anderson DR. Reproducibility of peripapillary retinal nerve fiber thickness measurements with stratus OCT in glaucomatous eyes. Ophthalmol. 2008;115(4):661-66. 
Kulkarni KM, Pasol J, Rosa PR, Lam BL. Differentiating mild papilledema and buried optic nerve head drusen using spectral domain optical coherence tomography. Ophthalmol. 2014;121(4):959-63.
Lee R, Tham YC, Cherung CY, Sidhartha E, Siantar RG, Lim SH, Wong TY, Cheng CY. Factors affecting signal strength in spectral-domain optical coherence tomography. Acta Ophthalmol. 2017. 




Figure 1. Trend of average retinal fiber layer thickness of patients with pseudopapilledema and papilledema superimposed on pseduopapilledema during serial follow-up. Longitudinal average RNFL thickness of (A) right and (B) left eye of patients with pseudopapilledema only. Longitudinal average RNFL thickness of (C) right and (D) left eye of patients with papilledema superimposed on pseudopapilledema.


Figure 2. Variability of average retinal fiber layer thickness of patients with pseudopapilledema and papilledema superimposed on pseduopapilledema during serial follow-up. Variability of average RNFL thickness from initial visit of (A) right and (B) left eye of patients with pseudopapilledema only. Variability of average RNFL thickness from initial visit (C) right and (D) left eye of patients with papilledema superimposed on pseudopapilledema.


Figure 3. Color fundus photos of right eye (A) of index case showing moderate papilledema with obscuration of all borders, elevation of nasal border, and peripapillary halo correlating with SD-OCT image of optic nerve head of right eye showing thickening of retinal nerve fiber layer with inward deflection of the retinal pigment epithelium/Bruchs membrane towards the vitreous (B) compared to color fundus photo of right eye (C) at most recent visit along with SD-OCT image of optic nerve head (D) with resolved papilledema following conservative management following a trial of weight-loss and close follow-up.

